### ISSUE TITLE
Proposal: Short-cut for opening an H5Store in read-only mode.

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#179]
### Feature description

I use the following code segment **very** often:

```
with job.data.open(mode='r') as data:
    pass
```

### Proposed solution

I would like to implement some kind of short cut for that to avoid the reptition, something like:

```
with job.data.ro() as data:
    pass
```

_I'm not sure that this is the optimal API for this, since it is pretty cryptic._

### Additional context

Opening HDF5-files in read-only mode for reading is important, because it minimizes the likelihood for data corruption, especially during parallel access without file locking.

**Comment by vyasr** [comment]
I'm fine with introducing some sort of API for this. I can brainstorm on what would be nice.

To be safest and to best match with the internal Python API, should we maybe change the default to read-only? In Python, `open(fn)` is read-only by default. This would have to wait since it's a breaking change, but in keeping with our general efforts to preserve data integrity that might make sense.

**Comment by csadorf** [comment]
> I'm fine with introducing some sort of API for this. I can brainstorm on what would be nice. 

👍 

> To be safest and to best match with the internal Python API, should we maybe change the default to read-only? In Python, `open(fn)` is read-only by default. This would have to wait since it's a breaking change, but in keeping with our general efforts to preserve data integrity that might make sense.

Read-only by default might be better, however than we need to have a similar short-cut for write-access. It's also a bit annoying, because some convenience API, such as storing (and modifying) pandas DataFrames requires mutable access, even when you are just reading it.

**Comment by vyasr** [comment]
Coming up with a nice API for this is hard. The best I've come up with is implementing various modes like: `job.data.read`, `job.data.write`, `job.data.readwrite`, etc, which is similar to what you suggested, just more explicit. An alternative is implementing a separate method in the `job` namespace, e.g. `job.read_data()` and `job.read_store($STORE_NAME)`. We could also implement separate context managers in the h5store module, such as `with ReadStore(job.data) as ds`, but at that point it's basically as verbose as the original version.

Hmm OK I don't know enough about the details to address the pandas-like issues. It seems like the implication of this issue is that reading is a more common operation than writing, which is almost certainly true; the catch is that you can already both read and write inside the context, there's just no guarantee of data integrity. Perhaps we should assess how crucial these need is; in what ways can data be corrupted if you only execute read operations? Are we just protecting against accidental user modifications, or are the potential problems outside user control if e.g. the script crashes? And is there any way we can be clever about handling that on the back-end, so maybe we maintain the current function to open in different modes explicitly, but the default mode is read-only unless the user tries to write something explicitly, at which point we internally reopen the file in write mode?

**Comment by csadorf** [comment]
I think the problem mainly occurs when running jobs and gathering a status at the same time. I always run into file locking issues, which is why I usually turn the HDF5 file locking off with `HDF5_USE_FILE_LOCKING=FALSE` (see [here](https://forum.hdfgroup.org/t/turn-off-file-locking/3809/5)).

Opening the file multiple times without locking requires opening them in read-only mode to avoid corruption.

**Comment by csadorf** [comment]
@vyasr @bdice How would you feel about the option to change the default behavior with some kind of config or environment variable? We could even check the value of `HDF5_USE_FILE_LOCKING` and advise the user to make that change based on its value.

**Comment by csadorf** [comment]
It would mean that program behave differently when executed in different environments. Maybe that's a terrible idea...

**Comment by bdice** [comment]
I think I would prefer to see the signac config used instead of environment variables, if that makes sense for this use case.

**Comment by vyasr** [comment]
I agree that I would prefer using signac config variables, I think that would be OK.

**Comment by csadorf** [comment]
I'm no longer convinced of using either environment or configuration variables to change the default opening-mode. In either case, the behavior of the program is changed in a substantial manner based on *where* it is executed. That is an invitation for the introduction of extremely hard to find and possibly dangerous bugs.

Examples for critical bugs:
 1. Defaulting `mode='r'` and then using `OSError` to check for file existence and triggering the write process. Executed somewhere else the program will just create an empty file and move on.
 2. Accidentally setting `mode='w'` and overwriting files everywhere.

I think this was a terrible idea and I would like to bury it as soon as possible. We initially set the default opening-mode to `a`, because that is the default opening-mode of `h5py.File`. So I would also recommend against changing the default mode.

I really see only one viable alternative here, and that is providing some kind of short-hand notation to set the mode. One option would be to alias `open()` with `__call__()`, so
```python
with job.data('r') as data:
    pass
```
would be equivalent to:
```python
with job.data.open('r') as data:
    pass
```
Would that be intuitive? Do we anticipate any other function that could be reasonably mapped to `__call__()`?

**Comment by vyasr** [comment]
The other possible use case I could imagine would be the `keys` method of `DictManager`. However, the primary use-case I would imagine there would be testing for membership; currently the `H5Store` class handles that, but not the `DictManager`. I think opening the file is probably the most natural option for `__call__`, though.

**Comment by csadorf** [comment]
> The other possible use case I could imagine would be the `keys` method of `DictManager`. However, the primary use-case I would imagine there would be testing for membership; currently the `H5Store` class handles that, but not the `DictManager`. I think opening the file is probably the most natural option for `__call__`, though.

I don't think I fully understand your possible alternative use case, could you provide a minimal example?

**Comment by bdice** [comment]
Another possibility is that calling `job.data()` returns a copy of the entire file as a dict, just as `job.sp()` returns a copy of the statepoint. I don't think this is very useful, though. I support aliasing `open()` with `__call__()` if you think it's helpful.

**Comment by vyasr** [comment]
I think that the behavior that would be **most** intuitive to me would be: `job.data.keys == job.data()`. However, I don't think that everyone else will think that way, and aliasing `__call__` to `open` is also reasonably intuitive and something easy to get used to. Neither Bradley's suggestion nor mine is as useful as aliasing `open` since mine reduces fewer keystrokes and Bradley's use case is expensive in a way that is probably undesirable for h5 files, so I think your suggestion is fine.

**Comment by csadorf** [comment]
While it seems that we are on the same page concerning the aliasing, I'm very confused as to why you would find `job.data.keys == job.data()` intuitive. The standard way to get a view or list of keys in Python is `.keys()` with the object itself presenting as an iterable that overloads said function: `keys = list(job.data)`. I don't think I have ever seen an example where the call-operator was overloaded in this way. Do you have an example maybe?

The reason that I'm somewhat persistent on this issue is that I want to make sure we're not missing anything here.

**Comment by vyasr** [comment]
I tried to help clarify it with my emphasis in the last comment, but apparently I just made it more confusing 😂. Here's how I explained my view to Bradley: I don't think there is any intuitive behavior for `job.data()`, I wouldn't expect it to do anything *a priori*. What I meant with my previous comment was that, If I was told that it did something and I had to guess, my best guess would be that it returned the keys. It's not intuitive, it's just less unintuitive to me than the other options; however, I don't think the difference is significant enough to merit reserving it for that purpose, and if we teach people that it's the preferred method for setting the file mode, they'll use it correctly.

**Comment by csadorf** [comment]
> I tried to help clarify it with my emphasis in the last comment, but apparently I just made it more confusing 😂. Here's how I explained my view to Bradley: I don't think there is any intuitive behavior for `job.data()`, I wouldn't expect it to do anything _a priori_. What I meant with my previous comment was that, If I was told that it did something and I had to guess, my best guess would be that it returned the keys. It's not intuitive, it's just less unintuitive to me than the other options; however, I don't think the difference is significant enough to merit reserving it for that purpose, and if we teach people that it's the preferred method for setting the file mode, they'll use it correctly.

Got it. 👍

**Comment by csadorf** [comment]
I don't think the need for a shortened API is pertinent as I anticipated when I originally created this.
