### ISSUE TITLE
Simplify redundancies in nested dict representations

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac#272]
### Feature description
Currently nested dicts within signac can be represented as (1) nested dicts, (2) tuples as dict keys, and (3) strings with dot notation. 

### Proposed solution

We've had some conversation, about whether it's a good idea to keep all three representations, or to simplify to (1) and (2) or (1) and (3) only. Related topic is issue #64 

Current thoughts are:

- Keeping tuples as dict keys notation means more readable and simpler to iterate over, but requires more refactoring.
- Keeping strings with dot notation is more consistent with our current usage in Collections, but means slightly (very slightly) slower performance because indexing requires splitting the string and less readable code because we'd be iterating over split strings.

**Comment by vyasr** [comment]
@vishav1771 this issue is the one we should solve before #268. As the issue describes, we need to centralize our logic for handling nested dicts as much as possible. I think the first step is to evaluate all the places in the code where we use different types of nested dictionaries. 

I unfortunately don't know exactly where each of these representations is used. Internally, collections use the dotted keys representation, so collections contain the logic. The files that probably use this kind of logic are `sync.py`, `diff.py`, `contrib/import_export.py`, `contrib/schema.py`, and `contrib/collection.py, but there may be others that I'm missing. In general, you can safely ignore any file that says that it's deprecated; we recently went through a deprecation cycle for entire modules, so you'll find some files with comments like
```
"""
THIS MODULE IS DEPRECATED!
"""
```
For an example, see `contrib/mpipool.py`.

Once you've identified the use-cases for each of these, we can plan steps forward. Realistically, I don't think we can reduce to a single representation because the dots in keys representation is so central to our collection and command line interfaces but is probably not the most natural for users. However, evaluating exactly how we use these more thoroughly might help reduce the redundancy, then we would know exactly what conversions need to be provided (regarding #268).

**Comment by vishav1771** [comment]
@vyasr  I have gone through the file to find the implementation of the nested dict. 
The use cases of different nested dict representations are :

- Nested Dict 
1. Storing statepoints in `JSON` files

-  Dotted Strings
1. Difference of Jobs in `diff.py` (we are returning nested dict though).
https://github.com/glotzerlab/signac/blob/c998edf1aa9215a67de5286bc5dbb88fe739e70b/signac/diff.py#L74-L82

2. Import and export 
https://github.com/glotzerlab/signac/blob/c998edf1aa9215a67de5286bc5dbb88fe739e70b/signac/contrib/import_export.py#L51-L56
https://github.com/glotzerlab/signac/blob/c998edf1aa9215a67de5286bc5dbb88fe739e70b/signac/contrib/import_export.py#L332-L338

3. For generating `index` in `collection.py` based on key. It repaces nested dict with `_DictPlaceHolder` and searching values in collection using `find`

4. Matching regex in some cases.

- Tuples as dict keys

1. Generating `job_statepoint_index` in `schema.py` 
 
2. Storing schema of a project in `schema.py` and printed by converting to dotted string representation. (Similar to the first case).

Functions used to change between representations:

1. `_traverse_filter` in `collection.py` - nested dict to dotted keys 
2. `_dotted_keys_to_nested_dicts` in `diff.py` - dotted to nested dict 
3. Tuples are generated using `split` on dotted string 

Please add if I miss something.

**Comment by vyasr** [comment]
Thanks @vishav1771 this list looks fairly comprehensive and I don't see any other examples that you have missed. @atravitz do you recall finding any other examples?

**Comment by atravitz** [comment]
Hi @vishav1771 , thanks for going over this! 

Based on their usage, I'm inclined to think we should simplify to (1) nested dicts and (3) strings w/ dot notation, which means rewrite the instances of (2) tuples at dot keys. 

I also wonder if it would be more appropriate to rename `_traverse_filter` to `nested_dicts_to_dotted_keys

**Comment by vishav1771** [comment]
> Based on the usage, I'm inclined to think we should simplify to (1) nested dicts and (3) strings w/ dot notation, which means rewrite the instances of (2) tuples as dict keys.

Okay, I'll start working on this. 

>I also think it would be appropriate to rename _traverse_filter to nested_dicts_to_dotted_keys for readability?

Renaming makes sense. Can we move  `nested_dicts_to_dotted_keys` and `_dotted_keys_to_nested_dicts` to `utility.py`? (just to generalize them)

**Comment by vyasr** [comment]
I think that would be a reasonable place to put it for now, yes. We plan to do some significant reorganization before v2.0, so it may get moved again, but for now that seems like a good place to put it.

**Comment by vishav1771** [comment]
I got some doubts. It may or may not be related to this issue.
In `format` for `ProjectSchema`, when `depth` is provided 
https://github.com/glotzerlab/signac/blob/3debe37ed1c287163bb05bd1842bb4dafe874047/signac/contrib/schema.py#L109-L118

Here we are converting tuple of keys to dict as 
```
{
('a','b','c','d') :'e';
}
```
to
``` 
{'a': {}, 'b': {}, 'c':{'d': 'e'}}
```
I don't think this is intended behaviour. Please verify!
P.S. I think intended behaviour is to convert the tuple to nested dict and pass to `pformat` with `depth`.

**Comment by vyasr** [comment]
Good catch! I can verify that you are correct. This is definitely not the intended behavior. Here's a sample script that demonstrates the problem:

```python
import signac
project = signac.init_project('SchemaTestProject')
project.open_job({'a': {'b': {'c': {'d': 'e'}}}}).init()
schema = project.detect_schema()
print(schema.format(depth=2))
```

Looking through our tests, we have multiple tests of `detect_schema` that verify that the `ProjectSchema` has the right contents and that calling things like `difference` have the right behavior, but none that verify the behavior of the formatting of the object for printing. To avoid duplicating work, I would add a test for that and mark it with `pytest.xfail`. When you switch to the dict of dicts representation, that test should start failing (assuming it handles this case correctly), at which point you can remove the `xfail` decorator.
