### ISSUE TITLE
Allow arbitrary vlen data in job.stores

### ISSUE THREAD

**Issue by shannon-moran** [glotzerlab/signac#288]
### Feature description

Not all data is uniformly sized-- for instance, an "array of arrays" that holds the size of each cluster at each timestep in a simulation. As the number of clusters will change over time, the length of the array with sizes will not be uniform for all timesteps. When one uses `job.stores` to put this into `hdf5`, one gets the error ``Object dtype dtype('O') has no native HDF5 equivalent``. This is because native HDF5 needs uniformly sized data.

It would be great if we could support arbitrary shaped data without resorting to hack-jobs like dictionaries (e.g. {0:array,1:array,...} with keys indicating the simulation frame).

### Proposed solution

HDF5 offers support for arbitrary length data: http://docs.h5py.org/en/latest/special.html?highlight=dtype#arbitrary-vlen-data

Enabling this might be non-trivial, but would address many use cases where data varies in length by timestep.

**Comment by vyasr** [comment]
@bdice any idea on how feasible this would be? Offhand I don't actually think this would be too difficult, I think you would just need to change the calls to `create_dataset` in `_h5set`, but perhaps there are details that I'm missing.

**Comment by bdice** [comment]
Since we're currently relying on `h5py` to handle dataset creation (we just set the value with `grp[key] = value`), we would have to put in a special layer to `_h5set` that checks for something that can be treated as a ragged lists-of-lists, e.g.

```python
try:
    assert not all(len(value[0]) == len(v) for v in value))
except:
    pass
else:
    # Determine basetype
    # Create vlen_dtype
    # Add dataset
```

This would be tricky to handle correctly if we're interested in anything beyond the case of a 2D ragged array of numbers. It looks like the `vlen_dtype` can be anything (including objects), which might allow it to work with a 3D ragged array, but I don't know if HDF5 can actually _store_ arbitrary types of variable length -- I only tested that `h5py` allows me to construct such a dtype. The assignment would need to be handled recursively somehow to handle the higher dimensional ragged arrays, but it's not clear if our current implementation or the `vlen_dtypes` would allow that.

I would advocate against a partial solution with only 2D ragged arrays -- we should solve the problem completely if we do it.

**Comment by mikemhenry** [comment]
Like issue #419 perhaps the solution is to catch the exception and then link to some documentation for how a user can handle this issue, instead of us making some choice that could be problematic, break backwards compatibility, or increase maintenance/testing burden.
