### ISSUE TITLE
Run test that require redis-server and mongo-server on CI

### ISSUE THREAD

**Issue by vishav1771** [glotzerlab/signac#374]
### Feature description

The tests added for testing the redis and mongo backends in synced collection API in #364  requires the redis-server and mongo-server to run on CI. Currently, they are being skipped.

### Proposed solution

Maybe be we can use options like [fakeredis](https://pypi.org/project/fakeredis/) and [birdisle](https://birdisle.readthedocs.io/en/latest/user.html)

**Comment by mikemhenry** [comment]
I'm not sure if mocking redis is the correct approach or if we should add redis-server to the CI. Either have it in the base image, spin up another image that has redis and that can talk to our CI, or install it as part of setting up our dependencies.

**Comment by bdice** [comment]
We must also ensure that we test both with _and without_ optional dependencies (e.g. Redis and Mongo).

**Comment by vyasr** [comment]
This issue is addressed in #464. I basically did what @mikemhenry suggested by adding extra Docker images that provide Redis/MongoDB support. Those images are enabled on the Linux machines, but not Mac, Windows, or PyPy, so @bdice's request to test both with and without those dependencies is satisfied. We're not testing the full matrix of possibilities, but I'm comfortable with this level of coverage since it requires minimal effort to maintain: we can use CircleCI's own images for this.

Regarding the installed services that aren't running, at this point I think all the relevant tests are flagged appropriately. I've run tests locally both with and without these services and not had issues (I think I fixed some a few weeks ago). Any future issues that pop up can be handled then.
