### ISSUE TITLE
Support NumPy "array-like" objects in synced collections.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#380]
### Feature description

I would like to be able to convert and store CuPy, Dask, or other array-like objects in the same way we transparently cast NumPy arrays to lists for storage in synced collections.

### Proposed solution

Currently we do a check like

```python
if isinstance(data, np.ndarray):
    data = data.tolist()
```

I _think_ the only code change would be to perform a different check for array-like objects and add a second conversion:

```python
if hasattr(data, '__array__'):  # data is array-like
    data = np.asarray(data).tolist()
```

The `np.asarray` call will convert any array-like object to a base `ndarray` instance, which we can then convert to a list and save as usual.

Testing will be slightly harder, but not too tough. The NumPy Developer Docs have a [nice example of a custom array-like object](https://numpy.org/devdocs/user/basics.dispatch.html) that could be used.

### Additional context

NEP 16: https://numpy.org/neps/nep-0016-abstract-array.html
NEP 18: https://numpy.org/neps/nep-0018-array-function-protocol.html
NEP 22: https://numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html

**Comment by vyasr** [comment]
I like this feature, but before we implement, I'll play devil's advocate. Should we instead move the other way and stop automatically serializing numpy arrays? The obvious knee-jerk reaction is "no, of course we should support numpy, so much of our data is numpy arrays." However, consider that in 2.0 we are dropping support for non-str keys in part because we can't represent them faithfully (see #316): under the hood we convert them to str. Similarly, is it expected behavior if you can do

```
x = np.random.rand(5)
job.doc.arr = x
assert type(job.doc.arr) == type(x)  # this will fail
```

One obvious counterargument is that numpy ducktypes lists to numpy arrays, so in many cases things will work as expected. However, there are also plenty of cases where it won't work (`job.doc.arr + 1` isn't valid, even though `x + 1` is), and there are subtle edge cases (possible `FutureWarning`s that are actually errors if you try to do comparisons with numpy arrays of strings). If we're going to force our users to convert `int` keys to `str`, maybe we should err on the side of safety here and also ask users to do `job.doc.arr = x.tolist()`. @glotzerlab/signac-committers would be curious to hear opinions.

**Comment by bdice** [comment]
@vyasr I think that's a solid argument. I have some additional thoughts.

Removing the feature could be a significant UX regression:
- I have not heard users complain about array/list conversions while saving/loading data (the example you posed with non-string keys was causing significant challenges for users, which is a clear distinction in my mind in favor of keeping the feature). In fact, I believe [we originally added support for transparent casting](https://bitbucket.org/glotzer/signac/pull-requests/71/feature-transparent-type-cast-of-numpy/diff) because it was highly requested (though I can't recall for sure). @csadorf might know.
- Personally, I would certainly miss the convenience of saving NumPy arrays if the feature were removed, especially for small 1D arrays or arrays of bools/ints where floating point precision doesn't play a role. In those cases, I don't _really_ care if the data is returned as a NumPy array or a list.
- I don't think the alternative `array.tolist()` is very well-known by NumPy users. And for scalar values, `value.item()` is virtually unheard of in the code I've seen (I only know about it because signac uses it).

Other considerations:
- Should scalars like `np.float64(3.14)` be auto-converted to the corresponding base type, even if automatic list conversion for NumPy arrays were removed? This might not be very safe for extended-precision types, but we're _probably already mishandling those_.
- I think "array-like" data should certainly be converted for use with the `H5Store` class, even if we decided to remove support in classes derived from `SyncedCollection`. This support is [handled through a different mechanism in `H5Store`](https://github.com/glotzerlab/signac/blob/7086d8981c926703a023654d1c59bbedcfae6298/signac/core/h5store.py#L107-L109) than in `SyncedCollection`.

**Comment by mikemhenry** [comment]
This is a tough one, my initial thoughts are that we do want a nice UX story here, espically since we are trying to "sell" signac to people who wouldn't self identify as strong python users. On the other hand, people who care about precision may not realize everything happening under the hood. I'll keep thinking about this but I think something like throwing a warning when we do things to make serialization but may affect precision and type on the return. With the warning we could link to some documentation that describes some of the pitfalls and best practices.

**Comment by csadorf** [comment]
I think I'm leaning towards @bdice argument here that a convenient API to store numerical data has worked out very well so far and there have been no obvious problems with the fact that the returned data are just lists. It seems that most users are well aware of the fact that wrapping Python objects into desired types is sometimes necessary and I assume that many NumPy users are aware of [`np.asarray()`](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html).

But I also see Vyas' point. Like @mikemhenry said, it's a really tough one.

**Comment by csadorf** [comment]
One thought I just had is that we could potentially implement [`__array_function__`](https://numpy.org/doc/stable/reference/arrays.classes.html#numpy.class.__array_function__) for our own types and thus make it easier for numerical arrays to be automatically converted on the receiving end? I believe that this might be an obvious use case for this.

**Comment by vyasr** [comment]
Perhaps a reasonable compromise would be to add a configuration variable `cast_external_types` or so that would be `'true'` by default to retain backwards compatibility, but could also be changed to `'warn'` or `'error'` depending on how safe the user wants to be. This is analogous to the pandas option `mode.chained_assignment`. We could then clearly document the pros and cons of allowing this behavior, and depending on how strict we want to be we could change the default (`'warn'` would probably be the best long-term compromise). Depending on the exact scope, for instance if this is only for array types, we could name it more specifically `cast_external_arrays`.

@csadorf I'm not quite sure what you had in mind. What is "the receiving end" in this case? Do you mean so that users can easily convert our types to numpy arrays? Just to make sure that we're on the same page, the `__array__` method determines how an object is coerced to a `numpy.ndarray` when `np.asarray` is called, while the `__array_function__` method is to dispatch numpy function calls to appropriate callables for non-numpy arrays (e.g. `np.concatenate([a, b, c])` for `cupy.array`). Calling `np.[as]array` on our list-like collections automatically works because they are iterable, which is enough for numpy. I don't think there's a need for `__array_function__` because we're not trying to enable direct operation on any of our objects in a numerical context, casting them to numpy arrays is the expected behavior. The problem case is that once a user provides us an array and we cast it to a (synced) list for storage, the information about its original type is lost and we can't convert back, leaving that responsibility (implicitly) to the user.

**Comment by csadorf** [comment]
I am not sure how exactly the `__array_function__` backend works, I just thought it would potentially enable something like `job.arr + 1` and automatically return a numpy array or so.

With respect to feature-flagging this. This also crossed my mind, but I think it's a bad idea, because it means that signac code would run very differently in differing environments in a fundamental way. Something we should avoid as much as possible.

**Comment by vyasr** [comment]
Ah I see what you were trying for. Yes, you could implement something like that. For the particular use case you're describing, since addition is a ufunc you would override `__array_ufunc__`, but that's a detail. That would certainly fix many cases by making our object behave more like a numpy array. It may even be possible with a combination of `__array_ufunc__` and `__array_function__` to make our classes behave close enough to numpy arrays, but it would be rather painful to actually do this thoroughly (see for instance the recent HOOMD PR by @b-butler enabling zero-copy access to snapshot data). It might be a lot of effort for potentially limited payoff, but is certainly a valid solution. @b-butler please weigh in, I reviewed your PR thoroughly and I know how to do this, but I didn't actually go through the process so I can't speak to how tedious it really is.

**Comment by b-butler** [comment]
I would say that just implementing `__array_ufunc__` and `__array_function__` and `__array_interface__` or `__array__` are fairly easy and not very tedious. The problem comes in when you want `job.doc.np_array.mean(axis=1) + np.ones(1)` or something. The latter is the tedious in HOOMD because I needed to guarantee that our array classes never allowed conversion to a standard NumPy array as long as the memory was pointing to the same location. It may be less tedious here since we aren't worried about returning a NumPy array something like,

````python
def __getattr__(self, attr):
    if attr.startswith('__array'):
        raise AttributeError("Necessary if not implmenting every __array__ method.")
    return getattr(np.array(self), attr)
````

Would likely work for most cases.

**Comment by vyasr** [comment]
OK, if your opinion is that the main overhead was handling all the `coerce*` behavior in the `HOOMDArray` then we could consider it. We should consider carefully whether there are any downsides to making the `SyncedList` class behave like a numpy array before we move forward, but at least it's a plausible option.

**Comment by b-butler** [comment]
That being said, if we keep the current behavior, adding a section to our docs with a title something like "Effectively using NumPy and Scientific Python Packages with signac" that goes into detail about what we do to NumPy arrays in job statepoints and docs. Maybe this by itself doesn't garner a whole section, but I don't see this behavior documented anywhere. We do recommend using the `Job.stores` for this, but it would be good to let users now we implicitly convert their data otherwise especially if they are using custom data types or anything else that could lead to unexpected behavior like the cases @vyasr mentioned.
