### ISSUE TITLE
Table of correspondences between CLI and Python API

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#412]
### Feature description

@vyasr suggested adding a table of correspondences between signac's CLI and the Python API as a follow-up to #401.

As an alternatively solution, I think it might be just as good to add links in the other direction (without a table) that go from CLI :arrow_right: Python API.

**Comment by vyasr** [comment]
I think the use cases are somewhat different. Adding the links from CLI to Python helps for the case of "how do I do X in Python", which is really nice for one-liners. The table would be more useful in the case of "how do I write a shell script using signac" if you're actually trying to use the CLI as the primary interface, in particular if you need to use signac with non-Python tools. At the moment I would say both of these are of equal (equally low) importance since we have very few full-time CLI users that we're aware of. However, if we want that community to grow (i.e. if we want the CLI to be a first-class interface to signac) I think the table would be better.
