### ISSUE TITLE
Optimize `Collection` for internal use in `Project`

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#664]
A possible optimization for signac 2.0 (or later) would be to reduce the amount of code we use in the `Collection` class when calling `Project.find_jobs`. See: https://github.com/glotzerlab/signac/blob/b29e0485c7998ba0c6d041e9ec15b533334d9b64/signac/contrib/project.py#L717

We copy a large amount of data used from the `Project`'s internal caches during the construction of a `Collection` and calling its `find` method. At the very least, we never use the `Collection`'s ability to interact with data on disk or its ability to automatically generate ids (primary keys) for new records in the context of a signac `Project`, so we could eliminate some logic there in a cut-down class.

_Originally posted by @bdice in https://github.com/glotzerlab/signac/issues/652#issuecomment-1002303783_

I attempted an optimization in 13f2a8fb205f65d49421f4f4009ee3d78d00f9bf but it was [unclear if copy/reference semantics would be correct in the resulting indices](https://github.com/glotzerlab/signac/pull/652#discussion_r777170033) outside the context of a signac `Project`'s limited usage of `Collection`. A smaller class that is designed for the actual use case of signac's `Project.find_jobs` could act as an internal cache with only the necessary logic (e.g. no file I/O or id generation).

**Comment by vyasr** [comment]
As I mentioned in https://github.com/glotzerlab/signac/pull/652#issuecomment-1002303783, I'm very rusty on Collection internals and would have to invest a few hours reading that code to make intelligent suggestions, but do you think the best path forward is a stripped down class or could we do this more simply by introducing options directly to the Collection? Would it be possible to make the class take fast paths under certain conditions suitable for signac's use?

**Comment by bdice** [comment]
Hmm. I think the stripped-down version would remove a number of irrelevant methods/properties/attributes and not just change the implementation of the existing methods/properties/attributes, so an option in the constructor does not sound like the right answer.

**Comment by vyasr** [comment]
If that is the result, would we still be using Collection internally in signac at all? Or would it make sense to just spin it out as a small separate package?

**Comment by bdice** [comment]
On the `next` branch, we only use `Collection` in a couple places. Both are internal methods, and both use internal methods/attributes of the `Collection` and not its public API! That suggests to me that the class isn't really structured in the way we need in order to consume its data for project indexing, and a slimmer replacement class would be ideal. On that note, we should not have `Collection` as a public API in v2.0, in my view.
- schema.py, in `_build_job_statepoint_index`: https://github.com/glotzerlab/signac/blob/6c48d8ffcb51f0ce530c12ed8e889ffb4531dc07/signac/contrib/schema.py#L64-L73
- project.py, in `_find_job_ids`: https://github.com/glotzerlab/signac/blob/6c48d8ffcb51f0ce530c12ed8e889ffb4531dc07/signac/contrib/project.py#L712

**Comment by vyasr** [comment]
@csadorf what are your thoughts here? The Collection has always felt a little out of place in signac. It's much more complex than what we ever really leveraged internally, although I hadn't gone as far as @bdice in analyzing our really requirements. I'm also not aware of many users of it; the only real recollection I have of it being pushed to its limits is when @harperic wanted to use it with gzipped files and did some significant work to improve it. If we move forward with #667 I'm inclined to remove it from signac altogether. @bdice agreed with removing it from the public API in his last post, and if we neither use it internally nor expose it I don't see a good reason to keep it. If we think it has real value to keep around, though, we could release it separately (like we are planning to release synced collections) after 2.0.

**Comment by csadorf** [comment]
@vyasr I think I'm a bit confused about what you mean with "much more complex than what we ever really leveraged internally". The primary purpose of the collection class is to implement  functions needed to index and search our _database on the file system_. The fact that we applied a bunch of internal optimizations that in part bypass caching and indexing mechanisms should not really distract from the fact that this class is very much needed for non-trivial queries.

I think that removing it from the public API and making it a pure implementational detail with 2.0 is justified irregardless of whether we keep distributing it with signac or add it as a dependency. I always advocated for releasing the collection (and synced collection for that matter) independently since I think that they could be useful in other contexts similar to other standalone-file-based databases such as sqlite.

**Comment by harperic** [comment]
I wanted to let you know that we still use Collections for a few of our projects and would use/appreciate a standalone Collection package!

**Comment by csadorf** [comment]
> > I wanted to let you know that we still use Collections for a few of our projects and would use/appreciate a standalone Collection package!
> 
> Thanks for chiming in @harperic! 😄 I'm curious - does it matter to you if you have a pip-installable package, or would it be sufficient to provide a single `collection.py` file that could be vendored (directly copied) into your projects and used like `from collection import Collection`?

Terrible distribution mechanism...

**Comment by bdice** [comment]
I am not interested in maintaining a standalone `Collection` package. It's not meant to be a distribution mechanism so much as an off-ramp for current users if we remove `Collection` from signac's API.

**Comment by csadorf** [comment]
Is maintaining a separate package significantly more work compared to maintaining it as part of this package?

**Comment by bdice** [comment]
I'd say it is a significant burden. [signac-dashboard's pull request list](https://github.com/glotzerlab/signac-dashboard/pulls?q=is%3Apr+is%3Aclosed) is my experience with maintaining a package that has virtually no active development, unless you just skip over providing documentation and CI and the like. I've maintained that because I think dashboard is fun and want to keep it up to the signac project-wide standards, but I wouldn't get the same kind of enjoyment from a single-file `Collection` package.

**Comment by csadorf** [comment]
Fair enough.

**Comment by bdice** [comment]
The number of users of `Collection` (excluding signac's internals) can probably be counted on one hand - my suggestion of vendoring a single `.py` file was to explore one way to shift the maintenance burden off of core signac developers while providing a nicer off-ramp than just deleting `Collection` from our API. For some cases, [mongita](https://github.com/scottrogowski/mongita) might be a better option than signac's `Collection` while providing a similar Mongo-like interface.

**Comment by csadorf** [comment]
I mean it seems like mongita and signac.Collection have basically the exact same scope and mission. But mongita seems to be fairly new so maybe not as well tested and fast as, who knows. And the reason that Collection would only have a handful of users, is because we do not maintain and advertise it as its own package.

**Comment by harperic** [comment]
Alternatively, since Collection is effectively a reduced implementation of pymongo and my group is one of the handful of users, we could always go about migrating to pymongo, or using mongita, or spinning off Collection and you could proceed as you'd like.

**Comment by vyasr** [comment]
> @vyasr I think I'm a bit confused about what you mean with "much more complex than what we ever really leveraged internally". The primary purpose of the collection class is to implement functions needed to index and search our _database on the file system_. The fact that we applied a bunch of internal optimizations that in part bypass caching and indexing mechanisms should not really distract from the fact that this class is very much needed for non-trivial queries.

What I mean by this is that the Collection has a lot of bells and whistles that we have not to my knowledge ever really leveraged with signac. While I agree that we need something like this class, I don't remember a time when we needed more than what #667 implements. Admittedly I joined the signac team a year or two after its inception, and perhaps I am not remembering some very early iterations from 4+ years ago at this point. Additionally, maybe some amount of performance optimizations were already directly implemented at the Project layer, so I may have missed the Collection's heyday :)

**Comment by csadorf** [comment]
@vyasr Ok, I guess I misunderstood what you meant by "complexity". To me, the largest complexity is the actual indexing and querying mechanism. The ability to open (compressed) files etc., are indeed features that are nice to have, but not strictly needed by signac projects. Some of these functions were added to aid in the development of these classes. Some others were added, because I always assumed that we would potentially spin-off the package in its own package. But the primary reason was probably that the scope and direction that signac as a whole would take was not clear yet. My initial vision was always to at least have the ability to use something like MongoDB as the primary backend, and things like the collection class served almost as "work-around" for environments where those were hard to come by, e.g., a cluster login or batch node. So, one would use `signac.Collection` primarily during data generation, and then MongoDB or the like during post-processing and analysis.

**Comment by vyasr** [comment]
Resolved in #667 and #683.
