### ISSUE TITLE
make synced collections a "hidden" package

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/signac#790]

**Comment by bdice** [comment]
@mikemhenry Is this targeting 1.x or 2.x (`next`)?

**Comment by kidrahahjo** [comment]
@vyasr @bdice @mikemhenry 
What does making it a hidden package mean? We expose `BufferedJSONAttrDict` from synced_collections from our API. Do we continue doing that and simply rename the package to `_synced_collection` or do we not package synced collection at all in our source distribution?

**Comment by bdice** [comment]
> Do we continue doing that and simply rename the package to `_synced_collection`

Yes. We will expose the `BufferedJSONAttrDict` class from that package in the public API, but `signac.synced_collections` will no longer be public.

**Comment by kidrahahjo** [comment]
Got it, thank you :)

**Comment by vyasr** [comment]
> > Do we continue doing that and simply rename the package to `_synced_collection`
> 
> Yes. We will expose the `BufferedJSONAttrDict` class from that package in the public API, but `signac.synced_collections` will no longer be public.

It's worth thinking through this a little bit with an eye to a future where we support different storage options. One of the goals for signac's future is to allow users to store metadata in a format other than JSON via the different backends that `synced_collections` supports. In that scenario, `Job.document` would no longer be a `BufferedJSONAttrDict`, but rather a `MongoDict`, for instance. Practically speaking, we need decide exactly what API promises we make for `statepoint` and `document` (`Job` or `Project`). Rather than thinking about "exposing" specific classes (which could change), we should think in terms of the API users should expect. Specifically, both the state point and the document are basically just dict-like objects that support attribute-based access to keys (I think we're stuck with attribute-based access, although I'd love to consider removing that in a 3.0 release...). Even buffering is just an implementation detail.

**Comment by vyasr** [comment]
Resolved in #807.
