### ISSUE TITLE
`signac statepoint` keys on the command line should be in a deterministic order

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#87]
**[Original report](https://bitbucket.org/glotzer/signac/issue/87) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

**Comment by mikemhenry** [comment]
@bdice is this still an issue/problem?  I can't access the OG report. I'm setting up a python2.7 env to test if its a dictionary hash issue.

**Comment by bdice** [comment]
@mikemhenry I think this issue was just a title, the "OG report" was just empty in the text body. 😉

At first I wasn't able to reproduce the problem, but now I have a working test case:
```bash
$ signac init asdf
Initialized project 'asdf'.
$ signac job -c '{"a": 1, "b": 2}'
8aacdb17187e6acf2b175d4aa08d7213
$ signac job -c '{"b": 1, "a": 2}'
5e4d14d82c320bafb2f1286fe486d1f8
$ signac statepoint
{"b": 1, "a": 2}
{"a": 1, "b": 2}
```
It seems that the order of the dictionary keys in `signac statepoint` is based on the order in which the JSON file was written. Of course, dictionaries are order-free, but the underlying representation has an order by the way it's written to disk. This issue is strictly to make statepoints more readable / comparable by human eyes, especially when they get long. I would be fine with skipping and closing this issue if others do not think it is important - I think this issue was created before we had the `signac schema` command, which I find extremely useful.

**Comment by csadorf** [comment]
I think making sure that all command line output is deterministic is important so that users can use tools like `grep` and `awk` effectively.

The _statepoint_ itself is never ordered except through implementation-imposed order. This is a purely presentation-related issue.

**Comment by mikemhenry** [comment]
So the output is deterministic since its in the same order the file was created, but it isn't what someone would expect, do we want to then do a alpha-numeric sort on the keys before printing (I am *not* suggesting we re-order the file)? I'm not sure what sort of performance issues we would run into since every state point will need to be sorted before printing

**Comment by csadorf** [comment]
You are correct, but I think keys should be ordered for presentation on the command line.

The performance hit should be relatively low, since the bottleneck is the disk-read in the majority of cases. If we are concerned about this, we can add an option that turns key-ordering off, e.g., `--no-sort-keys`.

**Comment by mikemhenry** [comment]
While working on this issue, I noticed that `--pretty` will sort the keys

```
$ signac statepoint --pretty
{'a': 1, 'b': 2}
{'a': 2, 'b': 1}
```
as does, _drum roll_ the `--sort` argument

```
$ signac statepoint --sort
{'a': 1, 'b': 2}
{'a': 2, 'b': 1}
```

This code was added in 83bbce50ea3ee50b5a20e9f25fc8be8de52b0922 so I think we are good now?

**Comment by csadorf** [comment]
Issue was previously resolved.
